"""
Automated Boundary Search Script (Multiprocessing with Live Dashboard).

Utilizes all available CPU cores to compute the nonlinear critical boundaries 
concurrently. Intercepts standard output from child processes to render a 
real-time, btop-style monitoring dashboard using the 'rich' library.
"""

import sys
import os
import multiprocessing
import time
from core import config
from critical_boundary_fem import AdaptiveFemAnalyzer

# Try importing rich for the UI dashboard
try:
    from rich.live import Live
    from rich.table import Table
    from rich import box
    from rich.console import Console
except ImportError:
    print("Error: The 'rich' library is required for the live dashboard.")
    print("Please install it by running: pip install rich")
    sys.exit(1)

class WorkerStdout:
    """
    Custom stdout interceptor to pipe worker prints into a multiprocessing queue.
    This completely hides the messy overlapping console outputs.
    """
    def __init__(self, queue, cid):
        self.queue = queue
        self.cid = cid
        self.buffer = ""
        
    def write(self, text):
        self.buffer += text
        while '\n' in self.buffer:
            line, self.buffer = self.buffer.split('\n', 1)
            line = line.strip()
            # Filter out purely decorative terminal lines generated by the script
            if line and not line.startswith('---') and not line.startswith('==='):
                self.queue.put((self.cid, line))
                
    def flush(self):
        pass

def worker_task(args):
    """
    Isolated worker process execution.
    """
    cid, queue = args
    
    # 1. Redirect standard output to the queue so it goes to our dashboard
    sys.stdout = WorkerStdout(queue, cid)
    
    # 2. Override configuration in isolated memory
    config.PARAMS["CASE_ID"] = cid
    config.PARAMS["BC_TYPE"] = "cantilever" if cid <= 4 else "simply_supported"
    
    queue.put((cid, f"[PID {os.getpid()}] Initializing solver..."))
    
    try:
        analyzer = AdaptiveFemAnalyzer(tolerance_percent=5.0)
        if cid in[3, 7, 9]:
            # Dual-variable cases: Generate 2D boundary curve
            analyzer.run(max_anchor_points=90)
        else:
            # Single-variable cases: Generate error evolution curve
            analyzer.run()
            
        queue.put((cid, "✅ Computation complete."))
    except Exception as e:
        queue.put((cid, f"❌ Error: {str(e)}"))
        
    return cid

if __name__ == '__main__':
    console = Console()
    console.clear()
    
    manager = multiprocessing.Manager()
    queue = manager.Queue()
    
    # Setup multiprocess arguments
    cases = [(cid, queue) for cid in range(1, 11)]
    status_dict = {cid: "⏳ Waiting for CPU allocation..." for cid in range(1, 11)}
    
    def generate_dashboard():
        """Generates the dynamic Rich table UI."""
        table = Table(box=box.ROUNDED, expand=True, title="[bold cyan]Geometrically Nonlinear Beam Analysis - Boundary Search Cluster")
        table.add_column("Case ID", justify="center", style="bold cyan", width=10)
        table.add_column("Problem Type", justify="center", style="bold magenta", width=18)
        table.add_column("Live Execution Status", justify="left", style="green")
        
        for cid in range(1, 11):
            ctype = "Bi-variable Scan" if cid in[3, 7, 9] else "Single-var Evolution"
            text = status_dict[cid]
            
            # Dynamic row color highlighting based on state
            if "✅" in text or "complete" in text.lower():
                row_style = "bold bright_green"
            elif "❌" in text or "error" in text.lower():
                row_style = "bold red"
            elif "Progress" in text or "Scanning" in text:
                row_style = "yellow"
            elif "Waiting" in text:
                row_style = "dim white"
            else:
                row_style = "white"
                
            table.add_row(f"Case {cid:02d}", ctype, text, style=row_style)
        return table

    start_time = time.time()
    
    # Reserve 1 CPU core to prevent system freeze during intense FEM computation
    cores = max(1, multiprocessing.cpu_count() - 1)
    
    # Start async multiprocessing pool
    pool = multiprocessing.Pool(processes=cores)
    result_async = pool.map_async(worker_task, cases)
    
    # Start the Live UI Loop (Refresh 10 times per second)
    with Live(generate_dashboard(), console=console, refresh_per_second=10) as live:
        while not result_async.ready():
            # Process all messages currently in the queue
            while not queue.empty():
                cid, msg = queue.get()
                status_dict[cid] = msg
            # Update the terminal UI
            live.update(generate_dashboard())
            time.sleep(0.05)
            
        # Final sweep to catch remaining messages after completion
        while not queue.empty():
            cid, msg = queue.get()
            status_dict[cid] = msg
        live.update(generate_dashboard())
        
    pool.close()
    pool.join()
    
    end_time = time.time()
    console.print(f"\n[bold green]Cluster execution finished successfully. Total elapsed time: {(end_time - start_time)/60:.2f} minutes.")
    console.print("[bold cyan]Results have been saved to 'results/boundary_analysis/'.")
