"""
Automated Boundary Search Script (Hybrid Multiprocessing with Live Dashboard).

Runs all ten nonlinear 5% FEM boundary/error analyses. Single-variable cases use
the original case-level multiprocessing dashboard, while the heavy bi-variable
cases (3, 7, 9) use the CPU-max chunk scheduler from run_boundary_cpu_max.py.
"""

import os

# Limit nested BLAS/OpenMP threading before importing NumPy/SciPy/OpenSees paths.
for _name in (
    "OMP_NUM_THREADS",
    "MKL_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "NUMEXPR_NUM_THREADS",
):
    os.environ[_name] = "1"
os.environ.setdefault("MPLBACKEND", "Agg")
os.environ.setdefault("MPLCONFIGDIR", "/tmp/euler_elastica_matplotlib")
os.makedirs(os.environ["MPLCONFIGDIR"], exist_ok=True)

import sys
import multiprocessing
import time
from core import config
from critical_boundary_fem import AdaptiveFemAnalyzer
from run_boundary_cpu_max import main as run_cpu_max_boundary

DUAL_VAR_CASES = [3, 7, 9]
SINGLE_VAR_CASES = [cid for cid in range(1, 11) if cid not in DUAL_VAR_CASES]

# Try importing rich for the UI dashboard
try:
    from rich.live import Live
    from rich.table import Table
    from rich import box
    from rich.console import Console
except ImportError:
    print("Error: The 'rich' library is required for the live dashboard.")
    print("Please install it by running: pip install rich")
    sys.exit(1)

class WorkerStdout:
    """
    Custom stdout interceptor to pipe worker prints into a multiprocessing queue.
    This completely hides the messy overlapping console outputs.
    """
    def __init__(self, queue, cid):
        self.queue = queue
        self.cid = cid
        self.buffer = ""
        
    def write(self, text):
        self.buffer += text
        while '\n' in self.buffer:
            line, self.buffer = self.buffer.split('\n', 1)
            line = line.strip()
            # Filter out purely decorative terminal lines generated by the script
            if line and not line.startswith('---') and not line.startswith('==='):
                self.queue.put((self.cid, line))
                
    def flush(self):
        pass

def worker_task(args):
    """
    Isolated worker process execution.
    """
    cid, queue = args
    
    # 1. Redirect standard output to the queue so it goes to our dashboard
    sys.stdout = WorkerStdout(queue, cid)
    
    # 2. Override configuration in isolated memory
    config.PARAMS["CASE_ID"] = cid
    config.PARAMS["BC_TYPE"] = "cantilever" if cid <= 4 else "simply_supported"
    
    queue.put((cid, f"[PID {os.getpid()}] Initializing solver..."))
    
    try:
        analyzer = AdaptiveFemAnalyzer(tolerance_percent=5.0)
        # Single-variable cases: Generate error evolution curve.
        # Bi-variable cases are handled by the CPU-max chunk scheduler below.
        analyzer.run()
            
        queue.put((cid, "✅ Computation complete."))
    except Exception as e:
        queue.put((cid, f"❌ Error: {str(e)}"))
        
    return cid

if __name__ == '__main__':
    console = Console()
    console.clear()
    
    manager = multiprocessing.Manager()
    queue = manager.Queue()
    
    # Setup multiprocess arguments for the single-variable cases only.
    cases = [(cid, queue) for cid in SINGLE_VAR_CASES]
    status_dict = {cid: "⏳ Waiting for CPU allocation..." for cid in range(1, 11)}
    for cid in DUAL_VAR_CASES:
        status_dict[cid] = "⏳ Queued for CPU-max chunk scheduler..."
    
    def generate_dashboard():
        """Generates the dynamic Rich table UI."""
        table = Table(box=box.ROUNDED, expand=True, title="[bold cyan]Geometrically Nonlinear Beam Analysis - Boundary Search Cluster")
        table.add_column("Case ID", justify="center", style="bold cyan", width=10)
        table.add_column("Problem Type", justify="center", style="bold magenta", width=18)
        table.add_column("Live Execution Status", justify="left", style="green")
        
        for cid in range(1, 11):
            ctype = "Bi-variable Scan" if cid in[3, 7, 9] else "Single-var Evolution"
            text = status_dict[cid]
            
            # Dynamic row color highlighting based on state
            if "✅" in text or "complete" in text.lower():
                row_style = "bold bright_green"
            elif "❌" in text or "error" in text.lower():
                row_style = "bold red"
            elif "Progress" in text or "Scanning" in text:
                row_style = "yellow"
            elif "Waiting" in text:
                row_style = "dim white"
            else:
                row_style = "white"
                
            table.add_row(f"Case {cid:02d}", ctype, text, style=row_style)
        return table

    start_time = time.time()
    
    # Reserve 1 CPU core to prevent system freeze during intense FEM computation
    cores = max(1, multiprocessing.cpu_count() - 1)
    
    # Start async multiprocessing pool for single-variable cases.
    pool = multiprocessing.Pool(processes=cores)
    result_async = pool.map_async(worker_task, cases)
    
    # Start the Live UI Loop (Refresh 10 times per second)
    with Live(generate_dashboard(), console=console, refresh_per_second=10) as live:
        while not result_async.ready():
            # Process all messages currently in the queue
            while not queue.empty():
                cid, msg = queue.get()
                status_dict[cid] = msg
            # Update the terminal UI
            live.update(generate_dashboard())
            time.sleep(0.05)
            
        # Final sweep to catch remaining messages after completion
        while not queue.empty():
            cid, msg = queue.get()
            status_dict[cid] = msg
        live.update(generate_dashboard())
        
    pool.close()
    pool.join()

    for cid in DUAL_VAR_CASES:
        status_dict[cid] = "🚀 Running CPU-max chunk scheduler..."

    console.print("\n[bold cyan]Starting CPU-max bi-variable boundary scheduler for Cases 3, 7, and 9...")
    rc = run_cpu_max_boundary([
        "--cases", "3", "7", "9",
        "--max-anchor-points", "90",
        "--chunk-size", "5",
        "--workers", "auto",
        "--start-method", "forkserver",
        "--suffix", "",
    ])
    if rc != 0:
        console.print(f"[bold red]CPU-max boundary scheduler failed with exit code {rc}.")
        sys.exit(rc)

    for cid in DUAL_VAR_CASES:
        status_dict[cid] = "✅ CPU-max boundary complete."
    
    end_time = time.time()
    console.print(f"\n[bold green]Cluster execution finished successfully. Total elapsed time: {(end_time - start_time)/60:.2f} minutes.")
    console.print("[bold cyan]Results have been saved to 'results/boundary_analysis/'.")
